-- ============================================================================
-- Yenepoya Student Portal - Supabase PostgreSQL Schema
-- Run this in your Supabase SQL Editor (https://supabase.com/dashboard/project/calovrlfwpqumvfgewvo/sql)
-- ============================================================================

-- 1. Create student_requests table
CREATE TABLE IF NOT EXISTS public.student_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id TEXT UNIQUE NOT NULL,
  student_name TEXT NOT NULL,
  campus_id TEXT NOT NULL,
  branch TEXT NOT NULL,
  year TEXT NOT NULL,
  partner TEXT DEFAULT 'Not Applicable',
  query TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  status TEXT DEFAULT 'Received (In Review)',
  status_type TEXT DEFAULT 'received',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Enable Row Level Security
ALTER TABLE public.student_requests ENABLE ROW LEVEL SECURITY;

-- 3. Create Public Access Policies
CREATE POLICY "Allow public insert" ON public.student_requests
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public select" ON public.student_requests
  FOR SELECT USING (true);

CREATE POLICY "Allow public update" ON public.student_requests
  FOR UPDATE USING (true);

CREATE POLICY "Allow public delete" ON public.student_requests
  FOR DELETE USING (true);

-- 4. Enable Realtime for live Admin Table synchronization
ALTER PUBLICATION supabase_realtime ADD TABLE public.student_requests;
